project:
  title: "Prospectus" # Project title
  type: website
  output-dir: _site/ # Website directory

website:
  page-navigation: true # Enable page navigation
  reader-mode: true # Enable reader mode
  site-url: "https://elaine77777.github.io/project_web/" # Website URL
  repo-url: https://github.com/Elaine77777/project_web # Repository URL
  repo-actions: [source, issue] # Repository actions
  sidebar:
    style: "docked" # Sidebar style
    search: true # Enable search
    collapse-level: 2 # Initial sidebar collapse level
    contents: # Sidebar contents
      - index.qmd
      - section: "Process"
        contents: process/*

      - section: "Reports"
        contents: reports/*
    tools:
      - icon: github
        href: https://github.com/Elaine77777/project_web

format:
  html:
    theme: cosmo # Bootstrap theme for the site
    toc: true # Enable table of contents

execute:
  freeze: auto # only render documents that have changed
